### ISSUE TITLE
IDE phase 2 system test feature writing and execution

### ISSUE THREAD

**Issue by brianlee731** [unity-sds/unity-system-test#21]
Write and test IDE verification test and procedures in unity-test environment.

Document test plan (.feature files), document test procedures (what you did), Document test results

**Comment by brianlee731** [comment]
Updated: To https://github.com/unity-sds/unity-system-test.git
   c3fd0d9..939fa85  issues/21 branch

**Comment by mike-gangl** [comment]
@brianlee731 this ticket needs an estimate

**Comment by GodwinShen** [comment]
@brianlee731 ping for status

**Comment by brianlee731** [comment]
Finished writing out the validation tests and now executing them. Link is here: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/milestones/view/2080
