### ISSUE TITLE
Data Catalog phase 2 system test feature writing and execution

### ISSUE THREAD

**Issue by brianlee731** [unity-sds/unity-system-test#22]
Write and test Data Catalog verification test and procedures in unity-test environment.

Document test plan (.feature files), document test procedures (what you did), Document test results

**Comment by mike-gangl** [comment]
@brianlee731 this ticket needs an estimate

**Comment by GodwinShen** [comment]
@brianlee731 ping for status

**Comment by brianlee731** [comment]
Finished writing out the validation test and executing the tests.
